### ISSUE TITLE
 node server4 error

### ISSUE THREAD

**Issue by openainext** [ClusterWS/ClusterWS-Tests#11]
node server4
PID: 26668
 TypeError: Cannot read property 'length' of undefined
    at E:\saas\ClusterWS-Tests-master\ClusterWS-Machine-Scale-Tests\index.js:309:42
    at BrokerServer (E:\saas\ClusterWS-Tests-master\ClusterWS-Machine-Scale-Tests\index.js:310:6)
    at Broker (E:\saas\ClusterWS-Tests-master\ClusterWS-Machine-Scale-Tests\index.js:369:28)
    at process.<anonymous> (E:\saas\ClusterWS-Tests-master\ClusterWS-Machine-Scale-Tests\index.js:375:50)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at process.nextTick (internal/child_process.js:755:12)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Broker has exited

**Comment by goriunov** [comment]
Yes i know about that, i have not modified `server4` for never version, how ever `server1 - server3` should work perfectly .
